AUTHORS.md, CHANGELOG.md, bricks/stm32/stm32.mk, pybricks/iodevices.h, pybricks/iodevices/pb_module_iodevices.c, pybricks/iodevices/pb_type_iodevices_lwp3device.c
Given that bluetooth communication with other devices than the remote was pushed forward on your timeline, I gave this a shot. 
These commits could provide a starting point to the LWP3Device class as mentioned here: [https://github.com/pybricks/support/issues/262#issuecomment-800903523](https://github.com/pybricks/support/issues/262#issuecomment-800903523)
This is tested on: Technic Hub/City Hub/Prime Hub, each connects/reads/writes successfully in combination with a City hub and Remote running the stock LEGO firmware. Mario was previously working but can currently not connect see: [https://github.com/pybricks/support/issues/442](https://github.com/pybricks/support/issues/442).
I am curious what your view is on this new feature, any feedback is welcome!
I will provide some code examples …
=> pybricks/experimental: Add LWP3Device.

lib/pbio/drv/bluetooth/bluetooth_stm32_cc2640.c
Set the scan timeout to infinite. To connect with bluetooth devices after 10 seconds, see issue [https://github.com/pybricks/support/issues/485](https://github.com/pybricks/support/issues/485)
Additionally the scanning intervals and scanning windows are set to 30ms, to match the scan interval on the prime/essential hubs.
=> pbio/drv/bluetooth_stm32_cc2640: scan timout inf

bricks/ev3dev/pb_type_ev3dev_font.c, bricks/ev3dev/pb_type_ev3dev_image.c, pybricks/common/pb_type_control.c, pybricks/common/pb_type_motor.c, pybricks/hubs/pb_type_cityhub.c, pybricks/hubs/pb_type_essentialhub.c, pybricks/hubs/pb_type_ev3brick.c, pybricks/hubs/pb_type_movehub.c, pybricks/hubs/pb_type_nxtbrick.c, pybricks/hubs/pb_type_primehub.c, pybricks/hubs/pb_type_technichub.c, pybricks/iodevices/pb_type_iodevices_ev3devsensor.c, pybricks/iodevices/pb_type_iodevices_lumpdevice.c, pybricks/nxtdevices/pb_type_nxtdevices_colorsensor.c, pybricks/pupdevices/pb_type_pupdevices_colordistancesensor.c, pybricks/pupdevices/pb_type_pupdevices_colorsensor.c, pybricks/pupdevices/pb_type_pupdevices_remote.c, pybricks/pupdevices/pb_type_pupdevices_ultrasonicsensor.c, pybricks/robotics/pb_type_drivebase.c, pybricks/robotics/pb_type_spikebase.c, pybricks/util_mp/pb_obj_helper.c, pybricks/util_mp/pb_obj_helper.h
This implements lookups for attributes like `hub.speaker` in Pybricks, without relying on [this patch](https://github.com/pybricks/micropython/commit/a98265f6a4108b6fbe5145f0d7532293ea05ca70) to upstream MicroPython.
It works with an attribute handler function instead of a special offset type in the `local_dict`.
Attribute offsets are stored in a static table. The attributes can be read/write/delete as needed. We only need read so far, but this is potentially more generic as well.
The size increase for the attribute handler function is fairly minimal since we get to drop the aforementioned patch as well. Still, it means we have to populate the `.attr` field on the respective types, so all in all this is about +152 bytes for Move Hub.
It also means we do an extra lookup in these types when …
=> Cleaner handling of object attributes

.github/build-each-commit.py, .github/workflows/build.yml
The `pull_request_target` trigger causes github actions to check out the master branch instead of the pull request branch. This is done for security reasons since `pull_request_target` is allowed access to secrets.
This modifies the build-each-commit.py script to be able to run without secrets so that it can be used for pull requests and adds a new conditional in the workflow to handle this case.
This should also fix building pull requests that are not based on the master branch.
=> github: fix build each commit for pull requests

lib/pbio/drv/charger/charger_mp2639a.c, lib/pbio/drv/resistor_ladder/resistor_ladder.c, lib/pbio/include/pbdrv/charger.h, pybricks/common/pb_type_charger.c
This is an (untested) work in progress to address the charger state detection, which doesn't seem to be quite right at the moment. This is explained in the commit messages.
This is mainly for discussion and needs some work (and testing) before merging.
This is the relevant piece of documentation:
=> Improve charger state detection

CONTRIBUTING.md, bricks/stm32/stm32.mk
The `deploy` target can deploy to any Hub as opposed to `deploy-dfu` that did not work for Inventor Hub without explicitly specifying `DFU_PID=0x0011`.
=> bricks/stm32: Removed obsolete `deploy-dfu` targets.

CHANGELOG.md, bricks/ev3dev/Makefile, bricks/ev3dev/pb_type_ev3dev_image.c, lib/contiki-core/sys/lc-switch.h, lib/contiki-core/sys/process.h, lib/pbio/drv/button/button_linux_ev3.c, pybricks/parameters/pb_type_color.c, pybricks/robotics/pb_type_drivebase.c, pybricks/util_mp/pb_kwarg_helper.h
Several of our upstream pull requests have been merged so we can drop the respective patches from our fork:
- py/gc: Add hook for events during garbage collect.  https://github.com/pybricks/micropython/commit/ba58e957343fab0cd9dc62c95eb380f9e09de7ee
- pybricks: STM32 UART fixes for BTStack https://github.com/pybricks/micropython/commit/ebf92a34a13e1511dec8e86092b597d2903b88af
- py/runtime: Init dest[1] in convert_member_lookup. https://github.com/pybricks/micropython/commit/c8a0ccb08619f1aa2e21863bfb9ee9692b036d81
- py/runtime: Optional lookup if type->attr fails. https://github.com/pybricks/micropython/commit/16a2a96e928046ea3dac4a9870731407fba355b3
- py/runtime: Return obj->attr for obj.attr if attr has offset type. https://github.com/pybricks/micropython/commit/a98265f6a4108b6fbe5145f0d …
=> micropython: Rebase to upstream master branch.

lib/pbio/test/src/uartdev.c
Hi, this PR is about typo fixs due to wrong copy/paste.
Comments are updated according to https://github.com/pybricks/technical-info/blob/master/assigned-numbers.md
=> Fix typos in device naming

CONTRIBUTING.md
exporting the path that was suggested before I get
FileNotFoundError: [Errno 2] No such file or directory: '/home/bene/lego/gcc-arm-none-eabi-*/bingcc'
when the correct path would be
/home/bene/lego/gcc-arm-none-eabi-10-2020-q4-major/bin/arm-none-eabi-gcc
=> fix export path in documentation

lib/pbio/include/pbsys/program_load.h, lib/pbio/sys/program_load.c, pybricks/common/pb_type_system.c
This feature has been requested many times (e.g. [here](https://www.eurobricks.com/forum/index.php?/forums/topic/186132-pybricks-qa/), [here](https://github.com/orgs/pybricks/discussions/623), or [here](https://github.com/pybricks/support/issues/85)). Now that we have enabled storage to save programs, we might as well add some storage for user data.
Proposed API:
```python
hub.system.storage(offset=5, write=b"Hello, world!")
data = hub.system.storage(offset=12, read=6)
print(data) # This will print b"world!"
```
Appropriate errors are be raised so read/write access is always safe.
We could also add a `storage_view` later on for hubs that can support it, but this should cover the basics.
=> pbsys/program_load: Add read/write access to user data.

CHANGELOG.md, bricks/_common/micropython.c, bricks/_common/mphalport.h, bricks/_common_stm32/mpconfigport.h, bricks/_common_stm32/mphalport.c, bricks/ev3rt/mpconfigport.h, bricks/ev3rt/mphalport.c, bricks/nxt/mpconfigport.h, bricks/nxt/mphalport.c, bricks/virtualhub/mp_port.c, lib/pbio/include/pbsys/main.h, lib/pbio/sys/command.c, lib/pbio/sys/program_stop.c, lib/pbio/sys/program_stop.h
If a user catches the `SystemExit` exception indefinitely, there is currently not a way to power off the hub.
This PR makes the following program exit normally so we can still de-init pbsys and do a clean power off.
```python
from pybricks.tools import wait
while True:
try:
wait(10)
except SystemExit:
print("nope!")
```
I'm not merging this yet because there may be a cleaner way to exit MicroPython using `PYEXEC_FORCED_EXIT` and / or various available hooks.
=> bricks/stm32: Force exit when shutdown requested.

CHANGELOG.md, bricks/_common/mpconfigport.h
This saves more than 2KB of build size. If we do this, it would be good to do this now, in time for V3.2.
The `micropython` module seems mostly useful for advanced users. For most users, having room for 2KB extra user code (or upcoming Bluetooth features) seems more useful. This module is made optional in https://github.com/micropython/micropython/pull/10131
Removing `uerrno` means a minor loss in clarity for error messages on Move Hub. But the terse errors are unclear to begin with, so something like https://github.com/pybricks/support/issues/817 could be done to improve it independent of this change.
=> Move Hub module optimization

CHANGELOG.md, bricks/_common/micropython.c
This avoids mentioning the stop button so that it is correct for all SystemExit or SystemAbort exceptions.
Fixes https://github.com/pybricks/support/issues/836
=> bricks/_common/micropython: Fix program stop message.

CHANGELOG.md, pybricks/util_pb/pb_task.c
Fixes https://github.com/pybricks/support/issues/814. This also works around things like https://github.com/pybricks/support/issues/567 so the user can at least turn the hub off without removing the batteries.
=> pybricks/util_pb/pb_task: Don't wait for cancel on shutdown.

CHANGELOG.md, lib/pbio/drv/imu/imu_lsm6ds3tr_c_stm32.c
The code found here:
https://github.com/pybricks/pybricks-micropython/blob/af76eecd6bfaff97c9e6435ed16d4bc97b9a946e/lib/pbio/drv/imu/imu_lsm6ds3tr_c_stm32.c#L283-L298
is sourcing both the accel and gyro values from the same source.
The original code was using the accel scaling and the data from the accelerometer, indices 0-2, while the gyro data is stored in indices 3-5 as notated here:
[pybricks-micropython/lib/pbi](https://github.com/pybricks/pybricks-micropython/blob/af76eecd6bfaff97c9e6435ed16d4bc97b9a946e/lib/pbio/drv/imu/imu_lsm6ds3tr_c_stm32.c#L240-L246)
This fork fixes the angular_rate function for all hubs to return the correct value in deg/s
=> Fixes gyro read using the wrong scaling and data indices for IMU data (angular_rate)

lib/pbio/drv/imu/imu_lsm6ds3tr_c_stm32.c
This should further reduce overhead.
=> pbio/drv/imu_lsm6ds3tr_c_stm32: Read gyro and acceleration in one pass.

bricks/ev3rt/README.md
As I have started some interest in EV3RT I have collected some useful links to generic resources about EV3RT that could be useful to maintainers and contributors of the EV3RT port of PyBricks.
This patch adds those links into `bricks/ev3rt/README.md` as a new section.
=> bricks/ev3rt: add more info about EV3RT in README

bricks/ev3dev/pbinit.c
Before the change, it looked like this. Speed estimates are way off:
After this change, it looks like this. The motor makes a perfect speed trapazoid:
=> Improve EV3 loop time and motor performance

.vscode/launch.json, bricks/virtualhub/mp_port.c, bricks/virtualhub/mpconfigvariant.h, bricks/virtualhub/mpvarianthal.h, lib/pbio/platform/virtual_hub/pbdrvconfig.h, lib/pbio/platform/virtual_hub/pbioconfig.h, lib/pbio/platform/virtual_hub/pbsysconfig.h, lib/pbio/platform/virtual_hub/platform.c, pybricks/hubs/pb_type_virtualhub.c, test-virtualhub.sh, tests/virtualhub/motor/drivebase.py
This uses the test drivers instead of the CPython implementation. This is easier to debug and maintain, and it runs a lot faster.
No specialized configuration is needed to run it anymore. You can just run the virtualhub-micropython executable as if it is normal MicroPython. It just so happens to have a working `pybricks` package.
The robot setup is defined in `platform.c`. It currently uses 5 motors, but this can be changed later to simulate a few sensors. Lights and buttons are not done yet, which is a regression for now.
The goal is to get to a virtualhub that we'll use more often (as opposed to using DFU on a real Prime Hub all the time). The existing implementation is very extensible and potentially very powerful, but sometimes a bit cumbersome to work with (which could be me).
This …
=> bricks/virtualhub: Build without CPython.

bricks/_common/arm_none_eabi.mk, bricks/virtualhub/Makefile
This appears to be necessary to build frozen modules now.
Is this the right way to do it?
Fixes:
```
CC ../../micropython/py/showbc.c
CC ../../micropython/py/repl.c
CC ../../micropython/py/smallint.c
CC ../../micropython/py/frozenmod.c
-e Error: micropython-lib submodule is not initialized. Run 'make submodules'  <-------
CC ../../micropython/extmod/machine_bitstream.c
CC ../../micropython/extmod/machine_i2c.c
```
=> bricks: Checkout micropython-lib.

.github/workflows/build.yml
Fixes `poetry: command not found` on pull requests.
=> .github/workflows/build: Install poetry before using it.

CHANGELOG.md, bricks/_common/sources.mk, bricks/cityhub/mpconfigport.h, bricks/debug/mpconfigport.h, bricks/essentialhub/mpconfigport.h, bricks/ev3dev/brickconfig.h, bricks/ev3rt/mpconfigport.h, bricks/movehub/mpconfigport.h, bricks/nxt/mpconfigport.h, bricks/primehub/mpconfigport.h, bricks/technichub/mpconfigport.h, bricks/virtualhub/mpconfigvariant.h, lib/BlueNRG-MS/hci/hci_le.c, lib/BlueNRG-MS/includes/hci_le.h, lib/pbio/drv/bluetooth/bluetooth_btstack.c, lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c, lib/pbio/drv/bluetooth/bluetooth_stm32_cc2640.c, lib/pbio/include/pbdrv/bluetooth.h, pybricks/common.h, pybricks/common/pb_type_ble.c, pybricks/hubs/pb_type_cityhub.c, pybricks/hubs/pb_type_essentialhub.c, pybricks/hubs/pb_type_movehub.c, pybricks/hubs/pb_type_primehub.c, pybricks/hubs/pb_type_technichub.c, pybricks/pybricks.c
This is an alternate attempt at hub to hub communication using BLE advertising data similar #80. (Thanks again @NStrijbosch and @laurensvalk  for all of the work done there.)
- Advertising and scanning and being connected to Pybricks Code and being connected to a remote on the Technic hub all at the same time seems to be working, so there is no background process to switch between advertising and scanning. The previous observed problems could have been caused by bugs in the existing Bluetooth driver code that have (hopefully) been fixed since then.
- Support for Move hub is added.
- Since LEGO has announced the discontinuation of MINDSTORMS, compatibility with the official firmware seems less important, so this has a different data encoding scheme and uses non-connectable advertisements. …
=> BLE Broadcast v2

CHANGELOG.md, bricks/ev3dev/Makefile, bricks/ev3dev/ev3dev_mphal.c, bricks/ev3dev/modules/core.py, bricks/virtualhub/mp_port.c, bricks/virtualhub/mpvarianthal.h, pybricks/tools/pb_module_tools.c
This adds a new non-blocking function to read one byte from stdin. This is needed since there is no other way to read from stdin on the Move hub. It is also useful on other hubs as it eliminates the need to use poll() to avoid blocking reads.
Fixes: https://github.com/pybricks/support/issues/1102
=> pybricks.tools: Add read_one() function.

CHANGELOG.md, bricks/cityhub/mpconfigport.h, bricks/debug/mpconfigport.h, bricks/essentialhub/mpconfigport.h, bricks/ev3dev/brickconfig.h, bricks/ev3rt/mpconfigport.h, bricks/movehub/mpconfigport.h, bricks/nxt/mpconfigport.h, bricks/primehub/mpconfigport.h, bricks/technichub/mpconfigport.h, bricks/virtualhub/mpconfigvariant.h, pybricks/tools/pb_module_tools.c
This implements the first approach discussed in https://github.com/pybricks/support/issues/1064.
```python
from pybricks.tools import hub_menu
selected = hub_menu("F", "D", "Z")
if selected == "F":
import fly_mission
elif selected == "D":
import drive_mission
elif selected == "Z":
import zigzag
```
This is really only applicable to systems with the light matrix, so maybe it belongs there? (Only that doesn't have buttons, so maybe not).
=> pybricks.tools: Add hub_menu function.

CHANGELOG.md, lib/pbio/drv/legodev/legodev_pup.c, lib/pbio/drv/legodev/legodev_pup.h, lib/pbio/drv/legodev/legodev_pup_uart.c, lib/pbio/test/src/test_uartdev.c
This keeps the device connection manager in control even if the UART device and PT threads get in a confused state.
Fixes https://github.com/pybricks/support/issues/1137
=> pbio/drv/legodev: Replace unplug reset by watchdog.

lib/pbio/drv/ioport/ioport_pup.c, lib/pbio/drv/legodev/legodev_pup.c
The city hub powers on the I/O ports (pin 4) during boot, so by the time the device connection manager detected a UART device, in many cases, it was too late to catch the device on the first sync. In the case of the BOOST color distance sensor, this meant waiting 10 seconds instead of 5 for the sensor to be ready.
This adds an option to enable a workaround for the quirk that cycles power to the I/O ports immediately after boot. This is faster than waiting for the next sync cycle.
Issue: https://github.com/pybricks/support/issues/747
=> drv/ioport_lpf2: add boot power quirk

CHANGELOG.md, lib/pbio/drv/core.c, lib/pbio/drv/ioport/ioport_pup.c, lib/pbio/drv/legodev/legodev_pup.c, lib/pbio/drv/legodev/legodev_pup.h, lib/pbio/drv/legodev/legodev_pup_uart.c, lib/pbio/drv/legodev/legodev_pup_uart.h, lib/pbio/drv/legodev/legodev_test.c, lib/pbio/drv/legodev/legodev_test.h, lib/pbio/drv/uart/uart.h, lib/pbio/drv/uart/uart_stm32f0.c, lib/pbio/drv/uart/uart_stm32f4_ll_irq.c, lib/pbio/drv/uart/uart_stm32l4_ll_dma.c, lib/pbio/platform/city_hub/pbdrvconfig.h, lib/pbio/platform/essential_hub/pbdrvconfig.h, lib/pbio/platform/move_hub/pbdrvconfig.h, lib/pbio/platform/prime_hub/pbdrvconfig.h, lib/pbio/platform/technic_hub/pbdrvconfig.h, lib/pbio/src/main.c, lib/pbio/test/src/test_uartdev.c
This implements a start to https://github.com/pybricks/support/issues/1140:
- This is a start to separating the device connection manager and the uart device code.
- Device synchronization is more likely to work in one go
- Disconnecting is handled more quickly because we can drop various timeouts
- Reduces code size on Move Hub by about 350 bytes
I have intentionally avoided much change to the `dcm` and `uartdev` code in this commit to make the change easier to process. We could do a few more cleanups though:
- Fix mixed use of `uartdev`, `data`, `port_data` name for the main data structure
- Fix names of the various protothreads: `data->pt` is not the same as `data_pt`, which can make it harder to follow.
- Now that the dcm and uartdev run separately from start to end, each can be a …
=> UART sensors cleanup

CHANGELOG.md, bricks/_common/sources.mk, lib/pbio/drv/led/led_pwm.c, lib/pbio/drv/led/led_virtual.c, lib/pbio/include/pbio/color.h, lib/pbio/include/pbio/int_math.h, lib/pbio/include/pbio/light.h, lib/pbio/src/color/conversion.c, lib/pbio/src/color/util.c, lib/pbio/src/int_math.c, lib/pbio/src/light/color_light.c, lib/pbio/test/src/test_color.c, lib/pbio/test/src/test_color_light.c, pybricks/common/pb_type_colorlight_internal.c, pybricks/parameters/pb_type_color.c, pybricks/pupdevices/pb_type_pupdevices_colorlightmatrix.c, pybricks/util_mp/pb_obj_helper.c, pybricks/util_pb/pb_color_map.c
This replaces #93, opting not to use libfixmath.
Uses the euclidean distance between colors when mapped into this HCL-bicone:
I've tested this quite a bit and found it to be robust. It can distinguish between black and dark bluish gray and NONE very reliably.
I also added calibrated default colors with the `BRICK_` prefix for a few standard lego colors and put them as new defaults. For now, I've chosen to use colors measured at a distance of 2 LEGO plates (=6.4 mm), but I have collected a lot of data so we can use other distance as well. If we chose colors at a larger distance, only their value will be lower, which might make the distance window larger to detect these colors rather than a darker one.
~~The `sensor.detectable_colors()` function now has a new kwarg `chroma_weight` which …
=> HCL bicone color distance function (without libfixmath)

CHANGELOG.md, lib/pbio/drv/bluetooth/bluetooth_btstack.c, lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c, lib/pbio/drv/bluetooth/bluetooth_stm32_cc2640.c, lib/pbio/include/pbdrv/bluetooth.h, pybricks/common/pb_type_ble.c
Fixes: https://github.com/pybricks/support/issues/1096
=> BLE observe fix

CHANGELOG.md, pybricks/pupdevices/pb_type_pupdevices_light.c
This makes no difference for the Light class, but it makes the class usable for certain custom devices.
-------------
This was requested by PV Productions to support their [USB output](https://pv-productions.com/product/usb-socket-cable/).
I'm not necessarily against this, although it might be better to add this kind of functionality to the `PUPDevice` class (or something like it) instead. Then it could be general purpose and useful for other third-party devices that might be wired up the other way around as well.
=> pybricks.pupdevices.Light: Invert default polarity.

CHANGELOG.md, pybricks/common/pb_type_device.c, pybricks/common/pb_type_device.h, pybricks/iodevices/pb_type_iodevices_pupdevice.c
Fix `pybricks.iodevices` not allowing writing -128 value (https://github.com/pybricks/support/issues/1366) and  raise informative error messages instead of clamping the input.
------
@antonvh - when this finishes building later this afternoon, you'll see zip files with the firmware with this fix. You can [install it using the advanced install option during hub selection](https://pybricks.com/install/spike-mindstorms/#installing-the-latest-build-advanced).
Does this fix the issue? You should be able to write -127 now.
=> pybricks.iodevices.PUPDevice: Fix data input checks.

bricks/movehub/mpconfigport.h, pybricks/common.h, pybricks/common/pb_type_keypad.c, pybricks/common/pb_type_system.c, pybricks/ev3devices/pb_type_ev3devices_infraredsensor.c, pybricks/hubs/pb_type_cityhub.c, pybricks/hubs/pb_type_essentialhub.c, pybricks/hubs/pb_type_ev3brick.c, pybricks/hubs/pb_type_movehub.c, pybricks/hubs/pb_type_nxtbrick.c, pybricks/hubs/pb_type_primehub.c, pybricks/hubs/pb_type_technichub.c, pybricks/hubs/pb_type_virtualhub.c, pybricks/iodevices/pb_type_iodevices_lwp3device.c, pybricks/parameters.h, pybricks/parameters/pb_module_parameters.c, pybricks/parameters/pb_type_button.c, pybricks/parameters/pb_type_button.h
This simplifies the button enum to make them more suitable beyond just pbio-specific keypad mappings. This will let them be used for other devices, like the Xbox Controller. (https://github.com/pybricks/support/issues/1488)
This also saves about 100 bytes on Move Hub. About half of this comes from omitting buttons that can't be used on Move Hub or with the remote, which we could theoretically also get without the dynamic enum (https://github.com/pybricks/support/issues/1453)
=> pybricks.common: Dynamically create button enum.

CHANGELOG.md, pybricks/tools/pb_module_tools.c
The default behavior remains the same, but you can now optionally do:
```python
read_input_byte(chr=True, last=True)
```
to apply the chr() function and discard all up to the last byte.
Applying `chr` is useful for remote controlling something with the keyboard, and simplifies the block code in https://github.com/pybricks/support/issues/1574
`last=True` can be useful for various things, including using the arrow keys, which when combined with `chr` will then simply map to A/B/C/D instead of having to parse three bytes and adding logic to find the last one.
=> pybricks.tools.read_input_byte: Allow chr conversion of last byte.

CHANGELOG.md, lib/pbio/sys/program_load.c
This is an experimental pull request to facilitate the use case in https://github.com/orgs/pybricks/discussions/1567.
This extends the readable region of user data to include the user code. This seems like a reasonable case for advanced users, so we might even choose to merge this.
The write-able region is not extended.
**NOTE**
If your purpose is to recover an existing program, naturally you mustn't override it with a new program to use this feature. Instead, use the REPL!
----------------------------
The ` hub.system.storage` method is normally used to read and store user data. Such as user light sensor calibration values. This is `512` bytes on SPIKE Prime. The user program size (4 bytes) and program follow immediately thereafter.
So, you can theoretically extract your user code using …
=> pbio/sys/program_load: Allow reading user program.

CHANGELOG.md, lib/pbio/include/pbio/protocol.h, lib/pbio/include/pbsys/bluetooth.h, lib/pbio/platform/city_hub/pbsysconfig.h, lib/pbio/platform/debug/pbsysconfig.h, lib/pbio/platform/essential_hub/pbsysconfig.h, lib/pbio/platform/ev3/pbsysconfig.h, lib/pbio/platform/ev3rt/pbsysconfig.h, lib/pbio/platform/move_hub/pbsysconfig.h, lib/pbio/platform/nxt/pbsysconfig.h, lib/pbio/platform/prime_hub/pbsysconfig.h, lib/pbio/platform/technic_hub/pbsysconfig.h, lib/pbio/platform/virtual_hub/pbsysconfig.h, lib/pbio/sys/bluetooth.c, lib/pbio/sys/core.c, lib/pbio/sys/hmi.c, lib/pbio/sys/light.c, lib/pbio/sys/light.h, lib/pbio/sys/supervisor.c, pybricks/common/pb_type_ble.c, pybricks/iodevices/pb_type_iodevices_lwp3device.c, pybricks/iodevices/pb_type_iodevices_xbox_controller.c
Implements toggling Bluetooth on and off with the Bluetooth button on Spike Prime and Mindstorms Robot Inventor.
See https://github.com/pybricks/support/issues/1615 for context, use cases, and user interface considerations.
This is a slightly more minimalist approach compared to #195. It adds `PBIO_PYBRICKS_STATUS_BLUETOOTH_BLE_ENABLED` to the protocol instead of `PBIO_PYBRICKS_STATUS_BLUETOOTH_BUTTON_PRESSED` and `PBIO_PYBRICKS_STATUS_BLUETOOTH_SHUTDOWN`.
The `hmi` is implemented similar to the existing code for the start/stop program button, and separated from the actual Bluetooth start/stop logic. The `hmi` may request a Bluetooth toggle, but it is up to `sys/bluetooth` whether to do anything with that. This prevents Bluetooth from being toggled if is currently being used or while a …
=> Allow Bluetooth to be toggled off/on with Bluetooth button.

lib/pbio/include/pbsys/program_load.h, lib/pbio/sys/program_load.c
We were using a separate "header" type with a known size so the program size could be a fixed remainder. But it isn't really a header since it contains user data, and soon also persistent system data.
We can accomplish the same statically allocated size by making the map (with unknown size program_data[] at the end) a union with the size of the writable block device.
=> pbio/sys/program_load: Use union to make fixed size.

CHANGELOG.md, bricks/_common/sources.mk, lib/pbio/include/pbsys/bluetooth.h, lib/pbio/include/pbsys/storage.h, lib/pbio/include/pbsys/storage_settings.h, lib/pbio/sys/bluetooth.c, lib/pbio/sys/bluetooth.h, lib/pbio/sys/command.c, lib/pbio/sys/hmi.c, lib/pbio/sys/storage.c, lib/pbio/sys/storage.h, lib/pbio/sys/storage_settings.c, pybricks/common/pb_type_ble.c, pybricks/iodevices/pb_type_iodevices_lwp3device.c, pybricks/iodevices/pb_type_iodevices_xbox_controller.c
Implements https://github.com/pybricks/support/issues/1622
Since validity is checked against the firmware version and programs are erased, we shouldn't need to reserve space for spare or yet unknown settings. This adds a single bool setting for the Bluetooth enabled state.
NB: This PR is against a non-master branch specifically to make review easier. This skips one blanket rename commit that didn't change any code.
------
Should `program_size` below also manually forced to be word aligned? It does seem to do it automatically right now.
Could also require the settings size to be word sized, but I'd be curious to hear what's the cleanest way to do it.
```c
/**
* System settings. All data types are little-endian.
*/
typedef struct _pbsys_storage_settings_t {
/**
* User has enabled Bluetooth …
```
=> pbio/sys/storage: Implement persistent storage.

CHANGELOG.md, bricks/_common/modules/_hub_extra.py, lib/pbio/drv/imu/imu_lsm6ds3tr_c_stm32.c, lib/pbio/include/pbio/imu.h, lib/pbio/include/pbsys/storage_settings.h, lib/pbio/src/imu.c, lib/pbio/sys/bluetooth.c, lib/pbio/sys/storage.c, lib/pbio/sys/storage.h, lib/pbio/sys/storage_settings.c, pybricks/common.h, pybricks/common/pb_type_imu.c, pybricks/hubs/pb_type_essentialhub.c, pybricks/hubs/pb_type_primehub.c, pybricks/hubs/pb_type_technichub.c
For rationale and usage, see https://github.com/pybricks/support/issues/1678
=> pbio/imu: Add user adjustable gyro correction.

CHANGELOG.md, lib/pbio/sys/hmi.c
Reduces the power off time from 3 to 2 seconds. This has been requested occasionally. I think this is OK.
If it makes certain use cases harder, like long press menus, we could now quite easily add a user setting to make this timeout configurable due to https://github.com/pybricks/support/issues/1622 now being implemented.
=> pbio/sys/hmi: Reduce time needed to power off hub.

bricks/_common/sources.mk, bricks/cityhub/mpconfigport.h, bricks/debug/mpconfigport.h, bricks/essentialhub/mpconfigport.h, bricks/ev3/mpconfigport.h, bricks/ev3dev/brickconfig.h, bricks/ev3rt/mpconfigport.h, bricks/movehub/mpconfigport.h, bricks/nxt/mpconfigport.h, bricks/primehub/mpconfigport.h, bricks/technichub/mpconfigport.h, bricks/virtualhub/mpconfigvariant.h, lib/pbio/drv/bluetooth/bluetooth_btstack.c, lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c, lib/pbio/drv/bluetooth/bluetooth_stm32_cc2640.c, lib/pbio/include/pbdrv/bluetooth.h, lib/pbio/include/pbio/protocol.h, lib/pbio/include/pbsys/command.h, lib/pbio/sys/command.c, pybricks/tools.h, pybricks/tools/pb_module_tools.c, pybricks/tools/pb_type_app_data.c, pybricks/tools/pb_type_hostbuffer.c
This adds a class that allows a user program to allocate a buffer for receiving data from an IDE.
It has similarities to receiving data over standard in, but it is a dedicated separate command. The data is not queued but (over)written to a fixed size buffer. This is a bit like downloading a program, but with user-readable data.
This is useful for applications where the buffer contains "sensor data"-like contents prepared by the IDE.
Usage is as follows:
```python
from pybricks.tools import HostBuffer
buffer = HostBuffer("hbb")
values = buffer.get_values()
data = buffer.get_bytes()
```
Before merging this as-is, it might be useful to thinking about the complementary case as well, where the user program can write data back to the IDE. This could facilitate things like live sensor port view …
=> pybricks.tools: Add hostbuffer to receive IDE data

CHANGELOG.md, pybricks/tools/pb_module_tools.c, pybricks/tools/pb_type_awaitable.c, pybricks/tools/pb_type_awaitable.h, tests/virtualhub/multitasking/basic.py
Fixes https://github.com/pybricks/support/issues/1429
Fixes https://github.com/pybricks/support/issues/1775
Fixes https://github.com/pybricks/support/issues/1460
Alternate for https://github.com/pybricks/pybricks-micropython/pull/262.
The following program now prints normally, while before it would print nothing.
```python
from pybricks.tools import multitask, run_task, wait
async def main1():
while True:
await wait(0)
async def main2():
while True:
print('Hello!')
await wait(500)
async def main():
await multitask(main1(), main2())
run_task(main())
```
=> pybricks.tools.wait: Fix awaiting on wait(0).

CHANGELOG.md, lib/pbio/include/pbio/protocol.h, lib/pbio/include/pbsys/light.h, lib/pbio/platform/city_hub/pbsysconfig.h, lib/pbio/platform/debug/pbsysconfig.h, lib/pbio/platform/essential_hub/pbsysconfig.h, lib/pbio/platform/ev3/pbsysconfig.h, lib/pbio/platform/ev3rt/pbsysconfig.h, lib/pbio/platform/move_hub/pbsysconfig.h, lib/pbio/platform/nxt/pbsysconfig.h, lib/pbio/platform/prime_hub/pbsysconfig.h, lib/pbio/platform/technic_hub/pbsysconfig.h, lib/pbio/platform/virtual_hub/pbsysconfig.h, lib/pbio/sys/bluetooth.c, lib/pbio/sys/core.c, lib/pbio/sys/light.c, lib/pbio/sys/light.h, lib/pbio/sys/storage_settings.c, pybricks/hubs/pb_type_cityhub.c, pybricks/hubs/pb_type_essentialhub.c, pybricks/hubs/pb_type_movehub.c, pybricks/hubs/pb_type_primehub.c, pybricks/hubs/pb_type_technichub.c, pybricks/hubs/pb_type_virtualhub.c
~~tl;dr: Use a subset of original light UI when Bluetooth is off (instead of inventing something new) so we don't lock ourselves into something when we release the upcoming beta.~~
----
~~https://github.com/pybricks/pybricks-micropython/pull/247 introduced the ability to toggle Bluetooth on and off. The main light UI was kept unchanged, and a blue (on) and red (off) Bluetooth light was added. As already stated in that issue and pull request, this UI was not ideal since there are too many lights, which can be confusing for users and competition judges. So we'd have to come up with something else before we can release the firmware in beta.~~
~~Instead of adding new lights, this PR makes it a subset of the existing UI. When Bluetooth is off, the hub status light is off when it would …
=> Refactor Bluetooth light UI. Use SPIKE Prime Bluetooth Light.

CHANGELOG.md, lib/pbio/src/light/animation.c, lib/pbio/test/src/test_animation.c, lib/pbio/test/src/test_color_light.c, lib/pbio/test/src/test_light_matrix.c, lib/pbio/test/test-pbio.h
Fixes https://github.com/pybricks/support/issues/1295 for both the hub light and the light matrix
=> pbio/light/animation: Fix lockup on restarting animation during animation frame.

CHANGELOG.md, pybricks/common/pb_type_ble.c, pybricks/hubs/pb_type_cityhub.c, pybricks/hubs/pb_type_essentialhub.c, pybricks/hubs/pb_type_movehub.c, pybricks/hubs/pb_type_primehub.c, pybricks/hubs/pb_type_technichub.c
This allows users to toggle observing off and on so that they can alternate between observing and broadcasting.
This results in better stability on Technic Hub which can lock up when simultaneous advertising and broadcasting.
Fixes https://github.com/pybricks/support/issues/1806
Also fix the remaining FIXME about the default broadcast channel while we are working on this code (first commit).
Usage:
```
hub.ble.observe_enable(True) # Enable observing (on by default)
hub.ble.observe_enable(False) # Disable observing
```
Can be combined with `hub.ble.broadcast(data)` and `hub.ble.broadcast(None)` to alternate between broadcasting and observing for better reliability on Technic Hub.
This isn't extensively tested yet, but making this available for others to try.
-------------
@NStrijbosch, …
=> pybricks.common.BLE: Implement observe_enable()

CHANGELOG.md, lib/pbio/include/pbdrv/usb.h, pybricks/common/pb_type_charger.c
Change return value of `connected()` property from `bool` to `int` using the value of `pbdrv_usb_get_bcd()`. This will allow pro users to be able to tell if they have a "nonstandard" charger that could prevent proper charging.
Related discussion: https://github.com/orgs/pybricks/discussions/1872#discussioncomment-11278180
Alternative to consider: We could have the battery status light reflect this status somehow to make it even easier for users. Although having programmatically accessible in addition to that still seems useful for advanced use cases.
=> pybricks.common.charger: change return value of connected()

bricks/_common/mpconfigport.h
This can be a useful performance tweak for some applications.
Probably not worth turning on on hubs with smaller RAM though.
=> bricks/_common/mpconfigport.h: enable MICROPY_GC_ALLOC_THRESHOLD

CHANGELOG.md, pybricks/common/pb_type_speaker.c
Return immediately if duration is negative as per documentation.
This works the same as with motor methods, with `wait=False` in that the method is not awaitable when duration is negative.
Issue: https://github.com/pybricks/support/issues/1996
=> pybricks.common.Speaker: fix negative duration in beep()

lib/lego/lego_usb.h
Swap the PIDs for the Robot Inventor hub and the Move hub. They don't follow the same patterns as SPIKE.
=> lego/usb: fix Robot Inventor USB PIDs

bricks/_common/mpconfigport.h
Remove MICROPY_ENABLE_SYSTEM_ABORT. It was replaced by MICROPY_ENABLE_VM_ABORT some time ago.
=> bricks/_common/mpconfigport: remove MICROPY_ENABLE_SYSTEM_ABORT

pybricks/common/pb_type_ble.c
With GCC 13 and -flto disabled, we were getting warnings like:
../../pybricks/common/pb_type_ble.c:291:21: error: array subscript 5 is outside the bounds of an interior zero-length array 'uint8_t[0]' {aka 'unsigned char[]'} [-Werror=zero-length-bounds]
291 |         value.v.data[5] = PB_BLE_BROADCAST_DATA_TYPE_SINGLE_OBJECT << 5;
|         ~
Instead of using the zero-length array, access the d member directly. This allows the compiler to actually check for out of bounds access and warn us about it.
=> pybricks.common.ble: fix compiler warning

bricks/_common/arm_none_eabi.mk, lib/pbio/drv/usb/stm32_usbd/usbd_conf.h, lib/pbio/drv/usb/stm32_usbd/usbd_desc.c, lib/pbio/drv/usb/stm32_usbd/usbd_pybricks.c, lib/pbio/drv/usb/stm32_usbd/usbd_pybricks.h, lib/pbio/drv/usb/usb_stm32.c, lib/pbio/include/pbdrv/usb.h, lib/pbio/include/pbio/protocol.h, lib/pbio/include/pbio/util.h, lib/pbio/platform/essential_hub/platform.c, lib/pbio/platform/prime_hub/platform.c, lib/pbio/src/protocol/pybricks.c, lib/pbio/src/util.c
Gets Windows to use the WinUSB driver for device. No other functionality is provided at this time.
See pybricks/pybricksdev#69 for changes to pybricksdev.
=> Add support for programming over USB

lib/pbio/drv/charger/charger_mp2639a.c, lib/pbio/include/pbdrv/charger.h, lib/pbio/platform/prime_hub/platform.c, lib/pbio/src/battery.c, lib/pbio/sys/battery.c
This takes initial steps towards resolving https://github.com/orgs/pybricks/discussions/1872.
This follows the observed pattern in the official firmware (MINDSTORMS and SPIKE V3) where charging is briefly disabled for some time after about half an hour of charging. This ensures that the charging chip does not time out and disables charging.
------------
To try it out, please download the firmware file in the post below and install it using [these instructions](https://pybricks.com/learn/getting-started/install-pybricks/#trying-the-nightly-version-optional).
-------------------
Some considerations: Is this really optimal? We could consider doing this only if the timeout error is really reached. This would reduce charge cycles.
@dlech …
=> Battery updates

CHANGELOG.md, pybricks/pupdevices/pb_type_pupdevices_colorsensor.c
This caused the `S` and `V` values to become negative on very bright TV screens.
Applications that used only the Hue value are unaffected.
=> pybricks.pupdevices.ColorSensor: Fix ambient HSV overflow.

lib/pbio/src/port_lump.c
It turns out the ColorLightMatrix needs the NACK to get going at all, so make sure we always send one before we start waiting on the keep-alive timeout. In b17e5033dcc4edd75722839c4832c791f0e698a8, we removed grace period of 6 keep-alive messages to go unanswered, which was essentially masking this issue so the device worked before.
=> pbio/port_lump: Fix ColorLightMatrix by sending initial NACK.

CHANGELOG.md, lib/pbio/drv/bluetooth/bluetooth_stm32_cc2640.c, pybricks/common/pb_type_ble.c
This partially fixes https://github.com/pybricks/support/issues/2206. I don't think there is a true cure but it turns out we can reduce the symptoms significantly.
We used to believe that alternating between observing and broadcasting  was the right workaround, but on closer look it appears that this might not be the case. The freezes are not random. When the Bluetooth chip locks up, it is always just after an observe restart. It will then get stuck at the very next Bluetooth command, whatever that is. That was usually broadcasting, so this is why we assumed they were conflicting.
So every time we restart observing, there is a small chance of locking up the Bluetooth chip. The restart was added in the first place as a workaround for the scan queue getting full so new scan events were not …
=> pbio/drv/bluetooth_stm32_cc2640: Only restart observe when needed.

bricks/_common/arm_none_eabi.mk, lib/pbio/drv/display/display_ev3.c, lib/pbio/platform/ev3/platform.ld, lib/pbio/platform/ev3/startup.s
=> EV3 linker cleanup

.github/workflows/build.yml, .github/workflows/release.yml, .github/workflows/stats.yml, bricks/_common/arm_none_eabi.mk, bricks/ev3/README.md
Replace creating a uImage with using the .elf file directly for the EV3 firmware. This simplifies the build process and avoids the need for u-boot-tools. U-Boot already knows how to load the .elf file, so we can use it directly by using `bootelf` instead of `bootm` (this change was made in the pybricks/v2.0.0 release of u-boot).
In order to keep the size of the .elf file small, we do not enable `-ffunction-sections` and `-fdata-sections` for the EV3 firmware. This avoids the large tables of section names that are generated by these flags, which would otherwise increase the size of the .elf file by nearly 200 kB. The .elf file is still a bit larger than the uImage because of a bit more overhead, but only by less than 4kB.
=> bricks/ev3: use .elf instead of uImage

bricks/_common/arm_none_eabi.mk
This fixes a potential issue with the .elf file copying over itself at the address where it was loaded.
=> bricks/ev3: bump u-boot to pybricks/v2.0.1

lib/pbio/drv/battery/battery_ev3.c
Implement reading the EV3 battery type from the GP8_8 pin.
Also make the remaining TODOs a bit more clear the the next person who works on this.
=> pbio/drv/battery/battery_ev3: implement EV3 battery type

.github/workflows/build.yml, .github/workflows/npm-firmware.yml, .github/workflows/npm-mpy-cross.yml, .github/workflows/release.yml, .github/workflows/stats.yml, lib/pbio/test/Makefile
Get a newer version of the cross compiler by using Ubuntu 24.04. This fixes some known issues with building the EV3 firmware.
=> github: bump CI to Ubuntu 24.04

CHANGELOG.md, lib/pbio/drv/bluetooth/bluetooth_stm32_bluenrg.c, lib/pbio/drv/bluetooth/bluetooth_stm32_cc2640.c, lib/pbio/drv/bluetooth/pybricks_service_server.c, lib/pbio/drv/usb/stm32_usbd/usbd_desc.c, lib/pbio/include/pbio/protocol.h, lib/pbio/include/pbsys/status.h, lib/pbio/platform/prime_hub/pbsysconfig.h, lib/pbio/platform/test/pbsysconfig.h, lib/pbio/src/protocol/pybricks.c, lib/pbio/sys/bluetooth.c, lib/pbio/sys/status.c
In order to support multiple program slots, connected apps will need to know how many slots are available on the hub and what the currently selected slot is. These are added to the hub capabilities and status report respectively and the Pybricks Profile version is bumped to 1.5.0.
=> pbio/protocol: add slots info to hub capabilities and status

bricks/virtualhub/mpconfigvariant.mk, pybricks/ev3devices/pb_module_ev3devices.c, pybricks/experimental/pb_module_experimental.c, pybricks/hubs/pb_module_hubs.c, pybricks/iodevices/pb_module_iodevices.c, pybricks/media/pb_module_media.c, pybricks/nxtdevices/pb_module_nxtdevices.c, pybricks/parameters/pb_module_parameters.c, pybricks/pupdevices/pb_module_pupdevices.c, pybricks/pybricks.c, pybricks/robotics/pb_module_robotics.c, pybricks/tools/pb_module_tools.c
Add a conditional compilation check around `MP_REGISTER_MODULE()` that checks `MICROPY_MODULE_BUILTIN_SUBPACKAGES`. If this option is enabled, we don't need to register subpackages as they are already handled by the parent package.
This corresponds to the alternate way of registering submodules at https://github.com/pybricks/pybricks-micropython/blob/343793b9a75f9460fd718b5aeb3a9f0e8e694ec9/pybricks/pybricks.c#L53-L84
But that requires enabling `MICROPY_ENABLE_EXTERNAL_IMPORT` which is pretty huge, so we'll stick with our method for now.
=> pybricks: modules: add conditional around MP_REGISTER_MODULE()

lib/pbio/drv/uart/uart_ev3.c
The PRU is on PSC 0, and so is UART0. However, UART1 is on PSC1. The existing code did not power on the correct peripherals at all, so just hard-code it to power on all three.
=> pbio/drv/uart/uart_ev3: Fix PSC powering-on of peripherals

bricks/_common/arm_none_eabi.mk, lib/pbio/drv/led/led_pwm.h, lib/pbio/drv/pwm/pwm_ev3.c, lib/pbio/drv/pwm/pwm_ev3.h, lib/pbio/platform/ev3/pbdrvconfig.h, lib/pbio/platform/ev3/platform.c, lib/pbio/platform/ev3/platform.ld, lib/tiam1808/drivers/pruss.c, lib/tiam1808/tiam1808/pruss.h
This is dependent on https://github.com/pybricks/pybricks-pru/pull/1 , and it needs to be modified to download the PRU binary rather than checking it into git (see related: https://github.com/pybricks/support/issues/2262 ), but I am opening the PR for now as the rest of the code is ready.
=> [EV3] Implement LED brightness control via software PWM on PRU1

bricks/_common/sources.mk, lib/pbio/drv/sound/beep_sampled.c, lib/pbio/drv/sound/sound_ev3.c, lib/pbio/include/pbdrv/sound.h, lib/pbio/platform/ev3/pbdrvconfig.h, lib/pbio/platform/nxt/pbdrvconfig.h, lib/pbio/platform/prime_hub/pbdrvconfig.h, lib/tiam1808/drivers/ehrpwm.c, lib/tiam1808/tiam1808/ehrpwm.h, pybricks/common/pb_type_speaker.c, pybricks/hubs/pb_type_ev3brick.c
This is a basic speaker driver for the EV3. The API surface exposed to user code is the same Speaker class as other hubs.
Unlike [v1](https://github.com/pybricks/pybricks-micropython/pull/341), this driver directly generates a square wave of the desired frequency rather than playing back samples.
As a consequence, it does not support volume control. However, it plays the full note range better than v1.
=> [v2] [EV3] Minimum-viable speaker driver

bricks/_common/sources.mk, lib/pbio/drv/block_device/block_device_ev3.c, lib/pbio/drv/reset/reset_ev3.c, lib/pbio/drv/reset/reset_ev3.h, lib/pbio/drv/watchdog/watchdog_ev3.c, lib/pbio/include/pbdrv/compiler.h, lib/pbio/platform/ev3/pbdrvconfig.h, lib/pbio/platform/ev3/platform.c, lib/pbio/platform/ev3/platform.ld
Implements both resetting as well as booting into firmware update mode.
~~Note that the ev3dev documentation is incorrect. The correct magic flag address is 0xFFFF1FF**C** and not 0xFFFF1FF**A**.~~ This issue has been corrected in the ev3dev documentation.
=> [EV3] Implement reset via watchdog timer

lib/pbio/drv/block_device/block_device_ev3.c
Fix a typo where the RX channel for the wrong SPI peripheral was requested. Likely we didn't notice this because everything should already be set up correctly by the bootloader since it also uses this SPI for flash memory.
=> pbio/drv/block_device_ev3: Fix RX DMA channel.

lib/pbio/drv/sound/sound_ev3.c
A frequency of 0 turns the sound off. It would previously play a minimum-frequency 64 Hz sound instead.
Fixes issue reported by @BertLindeman [here](https://github.com/pybricks/pybricks-micropython/pull/342#issuecomment-3092244006). Thanks for testing!
=> pbio/drv/sound/sound_ev3: Fix playing a frequency of 0

bricks/_common/micropython.c, bricks/_common_stm32/mphalport.c, lib/pbio/drv/usb/usb_stm32.c, lib/pbio/include/pbdrv/usb.h, lib/pbio/include/pbsys/host.h, lib/pbio/platform/city_hub/pbsysconfig.h, lib/pbio/platform/essential_hub/pbdrvconfig.h, lib/pbio/platform/essential_hub/pbsysconfig.h, lib/pbio/platform/ev3/pbsysconfig.h, lib/pbio/platform/move_hub/pbsysconfig.h, lib/pbio/platform/nxt/pbsysconfig.h, lib/pbio/platform/prime_hub/pbdrvconfig.h, lib/pbio/platform/prime_hub/pbsysconfig.h, lib/pbio/platform/technic_hub/pbsysconfig.h, lib/pbio/platform/test/pbsysconfig.h, lib/pbio/sys/bluetooth.c, lib/pbio/sys/bluetooth.h, lib/pbio/sys/command.c, lib/pbio/sys/host.c, lib/pbio/sys/main.c, lib/pbio/test/sys/test_bluetooth.c
The less ambitious alternative to https://github.com/pybricks/pybricks-micropython/pull/332.
This time, instead of duplicating a bunch of stuff, we finish the TODO to move the stdin buffer out of pbsys_bluetooth and into pbsys_host. Then we can hook up the USB stdin to this as well.
=> USB stdio v2

lib/pbio/drv/block_device/block_device_ev3.c, lib/pbio/drv/block_device/block_device_flash_stm32.c, lib/pbio/drv/block_device/block_device_test.c, lib/pbio/drv/block_device/block_device_w25qxx_stm32.c, lib/pbio/include/pbdrv/block_device.h, lib/pbio/platform/nxt/pbdrvconfig.h, lib/pbio/platform/nxt/pbsysconfig.h, lib/pbio/sys/storage.c, lib/pbio/sys/storage_data.h
Fix strict aliasing issues between block drivers and pbsys storage.
Casting a uint8_t* to a struct pointer violates strict aliasing rules, which can lead to hard-to-find bugs. We need to ensure that the memory being pointed to has the same alignment, etc. as the struct it is being cast to. The usual way to do this is to use a union of the struct and the other type we want to use (in this case, uint8_t array).
To do this, we need to move the storage data struct definition to a header file that can be included by both pbdrv/block_device and pbsys/storage.
Additionally, in block_device_test, the size of the ramdisk block was wrong and was causing the NXT to crash sometime after starting the REPL. It also incorrectly had the .noinit section attribute, but depends on being initialized to zero, …
=> pbio/sys/storage_data: fix strict aliasing issues

bricks/_common/arm_none_eabi.mk
This codebase already uses a number of C11 features. Enabling C11 globally will allow for UTF-16 string literals which are useful for USB.
=> bricks/_common/arm_none_eabi.mk: Switch to C11 standard

lib/pbio/drv/usb/usb_common_desc.c, lib/pbio/drv/usb/usb_ev3.c, lib/pbio/include/pbio/version.h, lib/tiam1808/drivers/usb.c
Fixing https://github.com/pybricks/support/issues/2295 plus bumping the firmware version so that the WebUSB descriptors point to `labs.pybricks.com` instead of `code.pybricks.com`.
=> EV3 USB fixes.

lib/pbio/drv/usb/usb_ev3.c
There is no guarantee that these events can only happen one at a time. If we happen to miss an event, it may cause the USB control transfer state machine to fall out of sync, which can cause enumeration failures.
This might fix https://github.com/pybricks/support/issues/2297
Note that the bulk of the diff is indentation changes.
=> [EV3] Fix more USB corner cases and minor bugs

bricks/_common/micropython.c, bricks/_common/sources.mk, lib/pbio/drv/cache/cache_ev3.c, lib/pbio/drv/sound/sound_ev3.c, lib/pbio/include/pbdrv/cache.h, lib/pbio/platform/ev3/pbdrvconfig.h, lib/pbio/platform/ev3/platform.c, lib/pbio/platform/ev3/platform.ld
* Enable EV3 speaker only upon first sound, as suggested [here](https://github.com/pybricks/support/issues/2155#issuecomment-3149603656)
* Rename EV3 caching macros, as suggested [here](https://github.com/pybricks/pybricks-micropython/pull/364#discussion_r2254707369)
* Fix MicroPython crash mentioned [here](https://github.com/pybricks/support/issues/2301)
* Mark `.dma` buffers as NOBITS
=> [EV3] Four misc fixups

lib/pbio/drv/uart/uart_ev3_pru_lib/pru.c, lib/pbio/drv/uart/uart_ev3_pru_lib/suart_api.c, lib/pbio/drv/uart/uart_ev3_pru_lib/suart_api.h, lib/pbio/drv/uart/uart_ev3_pru_lib/suart_pru_regs.h
Because we are already using PRU1, we cannot use dual-PRU mode for the SUART library. Remove support for this mode so that the code is easier to maintain and understand.
=> [EV3] Remove SUART code which we will not use

lib/pbio/platform/ev3/start.S
We are going to be keeping this cache/MMU disable code, so update the comment appropriately.
Also explain what the bit 13 in the control register does.
=> pbio/platform/ev3/start.S: Update comments for CPU setup

lib/pbio/platform/ev3/exceptionhandler.S
The bic opcode was supposed to be used here in order to *clear* the mode bits, rather than keep them.
This bug did not surface because we've mostly been hitting panics in System mode, which has a mode bits value of all 1s.
=> pbio/platform/ev3/exceptionhandler.S: Fix bug in panic handler

bricks/essentialhub/mpconfigport.h, bricks/nxt/mpconfigport.h
Remove a few duplicate or unused definitions in the hub mpconfigport.h files.
=> bricks/mpconfigport: remove duplicate/unused stuff

pybricks/tools/pb_type_matrix.c
Add type checking to fix a crash if the arguments to `cross()` are not `Matrix` objects.
=> pybricks.tools: Fix crash when cross() args are wrong type.

bricks/_common/micropython.c, bricks/_common/mpconfigport.h
This was missed in 65d519679ed2327abaf2d1669e521c3857819d30 when upgrading MicroPython. This would lead to programs being copied to RAM before running. How it was found: If all slots were full, then the program would not run as there would not be enough heap to load yet another program.
Also, MicroPython has a hardcoded test for mp_reader_mem_readbyte in mp_reader_try_read_rom, so it would ignore our reader even with MICROPY_VFS_ROM enabled.
Fixes https://github.com/pybricks/support/issues/2382
=> micropython: Bring back running program from storage RAM.
